[NFC][Comgr] Remove `DemangleTest` dependency with LLVM Support
Due to a header in gtest bringin in some llvm symbols, `DemangleTest`
depended on the abi-breaking checks; even though it used none.

Compilation failed with:
```
/usr/bin/ld:
tools/comgr/test-unit/CMakeFiles/DemangleSymbolNameTest.dir/DemangleSymbolNameTest.cpp.o:
undefined reference to symbol '_ZN4llvm23EnableABIBreakingChecksE'
/usr/bin/ld: _build/lib/libLLVMSupport.so.23.0git: error adding symbols: DSO missing from command line
```

This patch breaks the dependency by disabling gtest's LLVM extensions
for this test, since they're unused.